# Generated by Django 4.0.4 on 2022-05-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppComputadoras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesador',
            name='numeroModelo',
            field=models.CharField(max_length=50),
        ),
    ]
